git-svn-id: https://svn.apache.org/repos/asf/incubator/jena/Import/Jena-SVN/ARQ/trunk@1119988 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -2,6 +2,12 @@
 
 MODULE="$1"
 
+if [ "$MODULE" = "ARQ" ]
+then
+    echo "Error: can't snapshot ARQ to itself" 1>&2
+    exit 1
+    fi
+
 # Where to move the jars to
 if [ "$MODULE" != "" ]
 then
