Add support for alternative java to more commands

diff --git a/apache-jena/bin/xload-data b/apache-jena/bin/xload-data
--- a/apache-jena/bin/xload-data
+++ b/apache-jena/bin/xload-data
@@ -63,6 +63,25 @@ if [ -L "${JENA_HOME}" ]; then
   echo "Resolved symbolic links for JENA_HOME to $JENA_HOME"
 fi
 
+if [ -z "$JAVA" ]
+then
+    if [ -z "$JAVA_HOME" ]
+    then
+	JAVA="$(which java)"
+    else
+        JAVA="$JAVA_HOME/bin/java"
+    fi
+fi
+
+if [ -z "$JAVA" ]
+then
+    (
+	echo "Cannot find a Java JDK."
+	echo "Please set either set JAVA or JAVA_HOME and put java (>=Java 11) in your PATH."
+    ) 1>&2
+  exit 1
+fi
+
 if [ -e "${LOADER_SCRIPTS}/xload-common" ]; then
   # Can source common functions
   source "${LOADER_SCRIPTS}/xload-common"
@@ -283,7 +302,7 @@ DATA_QUADS="$LOC/data-quads.tmp"
 debug "Triples text files is $DATA_TRIPLES"
 debug "Quads text file is $DATA_QUADS"
 
-java $JVM_ARGS -cp "$JENA_CP" "$PKG".CmdNodeTableBuilder \
+"$JAVA" $JVM_ARGS -cp "$JENA_CP" "$PKG".CmdNodeTableBuilder \
     "--loc=$LOC" "--triples=$DATA_TRIPLES" "--quads=$DATA_QUADS" -- "${FILES[@]}"
 
 info "Data Load Phase Completed"
