JENA-1035: Set java executable via JAVA or JAVA_HOME

diff --git a/jena-fuseki2/apache-jena-fuseki/fuseki b/jena-fuseki2/apache-jena-fuseki/fuseki
--- a/jena-fuseki2/apache-jena-fuseki/fuseki
+++ b/jena-fuseki2/apache-jena-fuseki/fuseki
@@ -26,6 +26,7 @@
 #
 # JAVA
 #   Command to invoke Java. If not set, java (from the PATH) will be used.
+#   JAVA_HOME can also be used to set JAVA.
 #
 # JAVA_OPTIONS
 #   Extra options to pass to the JVM.
@@ -70,6 +71,7 @@
 # FUSEKI_LOGS_STDERROUT
 #   Log file with stderr and stdout log output from Fuseki. 
 #   Defaults to $FUSEKI_LOGS/stderrout.log
+
 
 ### BEGIN INIT INFO
 # Provides:          fuseki
@@ -248,12 +250,21 @@ fi
 # Set up JAVA if not set
 if [ -z "$JAVA" ]
 then
-  JAVA=$(which java)
+    if [ -z "$JAVA_HOME" ]
+    then
+       JAVA=$(which java)
+    else
+        JAVA=$JAVA_HOME/bin/java
+    fi
 fi
+
 if [ -z "$JAVA" ]
 then
-  echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.8) in your PATH." 1>&2
-  exit 1
+    (
+	echo "Cannot find a Java JDK."
+	echo "Please set either set JAVA or JAVA_HOME and put java (>=1.8) in your PATH."
+    ) 1>&2
+    exit 1
 fi
 
 # The location of the start up JAR
diff --git a/jena-fuseki2/jena-fuseki-core/fuseki-dev b/jena-fuseki2/jena-fuseki-core/fuseki-dev
--- a/jena-fuseki2/jena-fuseki-core/fuseki-dev
+++ b/jena-fuseki2/jena-fuseki-core/fuseki-dev
@@ -72,8 +72,29 @@ done
 ## exit
 
 FUSEKI_LOG="" #${FUSEKI_LOG:-}
-JVM_ARGS="${JVM_ARGS:--Xmx1200M}"
-exec java -cp "$CP" $JVM_ARGS $FUSEKI_LOG org.apache.jena.fuseki.cmd.FusekiCmd "$@"
+
+if [ -z "$JAVA" ]
+then
+    if [ -z "$JAVA_HOME" ]
+    then
+       JAVA=$(which java)
+    else
+        JAVA=$JAVA_HOME/bin/java
+    fi
+fi
+
+if [ -z "$JAVA" ]
+then
+    (
+	echo "Cannot find a Java JDK."
+	echo "Please set either set JAVA or JAVA_HOME and put java (>=1.8) in your PATH."
+    ) 1>&2
+  exit 1
+fi
+
+JVM_ARGS=${JVM_ARGS:--Xmx1200M}
+
+exec "$JAVA" -cp "$CP" $JVM_ARGS $FUSEKI_LOG org.apache.jena.fuseki.cmd.FusekiCmd "$@"
 
 # Run as war file.
 # java -jar jetty-runner.jar fuseki-server.war
