Correct redirection

diff --git a/jena-fuseki2/apache-jena-fuseki/fuseki b/jena-fuseki2/apache-jena-fuseki/fuseki
--- a/jena-fuseki2/apache-jena-fuseki/fuseki
+++ b/jena-fuseki2/apache-jena-fuseki/fuseki
@@ -252,7 +252,7 @@ then
 fi
 if [ -z "$JAVA" ]
 then
-  echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.8) in your PATH." 2>&2
+  echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.8) in your PATH." 1>&2
   exit 1
 fi
 
