GH-1328: Update SHACLC parser to javacc 7.0

diff --git a/jena-shacl/shaclc/shaclc-parser b/jena-shacl/shaclc/shaclc-parser
--- a/jena-shacl/shaclc/shaclc-parser
+++ b/jena-shacl/shaclc/shaclc-parser
@@ -1,39 +1,43 @@
 #!/bin/bash
-## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
+## Licensed to the Apache Software Foundation (ASF) under one
+## or more contributor license agreements.  See the NOTICE file
+## distributed with this work for additional information
+## regarding copyright ownership.  The ASF licenses this file
+## to you under the Apache License, Version 2.0 (the
+## "License"); you may not use this file except in compliance
+## with the License.  You may obtain a copy of the License at
+##
+##     http://www.apache.org/licenses/LICENSE-2.0
+##
+## Unless required by applicable law or agreed to in writing, software
+## distributed under the License is distributed on an "AS IS" BASIS,
+## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+## See the License for the specific language governing permissions and
+## limitations under the License.
 
-if [ $# -gt 1 ]
-then
-    echo "Usage: $0 FILE" 1>&2
-    exit 1
-    fi
-
-
-FILE="${1:-shaclc.jj}"
 DIR=../src/main/java/org/apache/jena/shacl/compact/reader/parser
+FILE="shaclc.jj"
+CLASS=ShaclCompactParserJJ
 
-rm -f "$DIR"/*
+(cd "$DIR" ; rm -f *.java )
 
 javacc -OUTPUT_DIRECTORY=$DIR  -JDK_VERSION=1.8 "${FILE}"
+
 RC=$?
-if [ "$RC" -ne 0 ]
-then
-    exit
-fi
+[ "$RC" = 0 ] || exit $RC
 
-## Fixup.
-#Token.java : public String toString()
-#TokenMgrError.java : public String getMessage()
-
-echo "---- Fixing Java warnings in Token ..."
-F="$DIR/Token.java"
-sed -e 's/@Override //' \
-    -e 's/public String toString/@Override public String toString/' < $F > F
-mv F $F
-
-echo "---- Fixing Java warnings in TokenMgrError ..."
-# Override:
-#   public String getMessage()
+echo "---- Fixing Java warnings in TokenMgrError"
 F="$DIR/TokenMgrError.java"
-sed -e 's/@Override //' \
-    -e 's/public String getMessage/@Override public String getMessage/' < $F > F
+if [ -e "$F" ]
+then
+    sed -e 's/public class TokenMgrError/\n@SuppressWarnings("all")\npublic class TokenMgrError/' < $F > F 
+    mv F $F
+fi
+    
+echo "---- Fixing Java warnings in ${CLASS} ..."
+F="$DIR/${CLASS}.java"
+sed -e 's/@SuppressWarnings("serial")//' \
+    < $F > F
 mv F $F
+
+echo "---- Done"
